version: "3.3"

services:
  rstudio:
    image: davidmacer/rstudio
    container_name: rstudio-descriptor
    restart: always
    volumes:
      - type: volume
        source: rstudio
        target: /app
      - type: bind
        source: .
        target: /home/rstudio
    network_mode: database_database_network
    environment:
      - PASSWORD=rstudio
    ports:
      - "3000:8787"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cont-descriptor
    restart: always
    volumes: 
      - ./app/:/srv/shiny-server/
    ports: 
      - "3001:3838"
      
volumes:
  app:
  rstudio:
